# Grid Size
CELL_SIZE = 30 
SCREEN_WIDTH = 1000
SCREEN_HIGHT = 850
GRID_ROWS = SCREEN_HIGHT // CELL_SIZE
GRID_COLUMNS = SCREEN_WIDTH // CELL_SIZE
ROW_MARGE = (SCREEN_WIDTH - (CELL_SIZE * GRID_COLUMNS)) / 2
COLUMN_MARGE = (SCREEN_HIGHT - (CELL_SIZE * GRID_ROWS)) / 2

MAZE_GRID_ROWS = GRID_ROWS - 2
MAZE_GRID_COLUMNS = GRID_COLUMNS
MAZE_LEVEL_START_X = (-SCREEN_WIDTH / 2) + ROW_MARGE + CELL_SIZE / 2
MAZE_LEVEL_START_Y = (SCREEN_HIGHT / 2) - COLUMN_MARGE - (CELL_SIZE * 5 / 2)

PLAYER_MOVE_SPEED = 6

ENEMY_NUMBER = 7
ENEMY_MOVE_SPEED = 5
ENEMY_RADAR = CELL_SIZE * 5

